### ISSUE TITLE
[DOCS] Build a `DIRECTORY.md` file automatically

### ISSUE THREAD

**Issue by Panquesito7** [TheAlgorithms/Jule#13]
### Description

Just like other repositories do, we can automatically create a `DIRECTORY.md` file with a list of all algorithms.
This will make it much easier when adding new algorithms as well as keeping the readme file clean.

We can either:

- Use the [workflow script](https://github.com/TheAlgorithms/scripts/tree/main/directory_md) written in Python.
- Create our own directory builder written in Jule. I recommend this as it will expand the language even more.

Let me know your thoughts. Thanks. 🙂

**Comment by mertcandav** [comment]
I did an experimental work on my own branch, if you see fit, I will work on it to PR with a clean new fork. Script is written entirely in Pure Jule. It creates an updated `DIRECTORY.md` when there are any changes in the tracked packages and commits it with the GitHub Actions account.

You can check the relevant branch in my fork to review: [here is the my fork and branch](https://github.com/mertcandav/TheAlgo-Jule/tree/directory)
