### ISSUE TITLE
[FEAT] Provide a test file for each of the algorithms

### ISSUE THREAD

**Issue by Panquesito7** [TheAlgorithms/Jule#14]
### Description

Currently, all of the tests are stored in one big test file, which is awesome to have tests, but I don't think it's the best way to structure/organize them.
I suggest:

- Create a unique `tests` folder.
- The folder should contain a file for each algorithm with the algorithm's name, but with the given tests.
- This might require the current algorithms to be re-organized or changed, but I think it's going to be better in the future and will make it much easier to look at when there are more implementations.

Let me know what you think. Thanks. 🙂

**Comment by mertcandav** [comment]
I opened a PR about it.
Please let me know what you think.
